apiVersion: v1
kind: ConfigMap
metadata:
  name: report-utils-py
  labels:
    app: readme-project
  namespace: default
data:
  report_utils.py: |
    # Utilitário para gerar relatório de aderência dos READMEs
    import json

    def generate_report(results, output_path):
      """Gera um relatório simples em JSON com a contagem de aderentes e não aderentes."""
      aderente = [r for r in results if r['status'] == 'Aderente']
      nao_aderente = [r for r in results if r['status'] == 'Não aderente']
      report = {
        'total': len(results),
        'aderente': len(aderente),
        'nao_aderente': len(nao_aderente),
        'detalhes': results
      }
      with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(report, f, ensure_ascii=False, indent=2)
